# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
 schedule:
 - cron: "0 7 * * *"

name: Render SalinityUpdate 

jobs:
  render:
    name: Render SalinityUpdate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install packages
        run: Rscript -e 'devtools::install_github("SwampThingPaul/AnalystHelper")'
      - name: Install packages
        run: Rscript -e 'install.packages(c("rmarkdown","knitr","dataRetrieval","lubridate","plyr","reshape","zoo","colorRamps","RcppRoll","maptools","classInt","GISTools","leaflet"))'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("SalinityUpdate.Rmd")'
      - name: Commit results
        run: |
          git commit README.md -m 'Re-build SalinityUpdate.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
